### ISSUE TITLE
Incomplete line?

### ISSUE THREAD

**Issue by danry25** [blu3Alien/xfinityfreewifi#1]
It looks like [line 22 of the login.sh script](https://github.com/blu3Alien/xfinityfreewifi/blob/9cc7dafa58ec44fc272b2bfe63d815f9c52dc3d6/login.sh#L22) got cut off? I don't see how it could get the URL to curl in its current state.

**Comment by blu3Alien** [comment]
The login function was never complete. I was intending to automate the web portal but ended up doing it manually. This portal has been updated multiple times since I created this script which would break it each time. The magic of the script is to generate a random mac address every hour for free internet that can be used on the Hak5 Pineapple.

Thanks for checking out the code, and this feature might be implemented in the future.
